### ISSUE TITLE
Android crashes when broadcast data contains unsupported type

### ISSUE THREAD

**Issue by amitkot** [kevlatus/flutter_broadcasts#4]
Using this package, when the broadcast contains a type that is unsupported by Flutter engine's [`StandardMessageCodec`](https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/plugin/common/StandardMessageCodec.java) class, the app crashes:

```
D/CustomBroadcastReceiver( 8169): received intent android.bluetooth.headset.profile.action.AUDIO_STATE_CHANGED
D/AndroidRuntime( 8169): Shutting down VM
E/AndroidRuntime( 8169): FATAL EXCEPTION: main
E/AndroidRuntime( 8169): Process: io.uglabs.ug_app, PID: 8169
E/AndroidRuntime( 8169): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.headset.profile.action.AUDIO_STATE_CHANGED flg=0x10 (has extras) } in de.kevlatus.flutter_broadcasts.CustomBroadcastReceiver@80fdd34
E/AndroidRuntime( 8169):  at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1816)
E/AndroidRuntime( 8169):  at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime( 8169):  at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 8169):  at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 8169):  at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime( 8169):  at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime( 8169):  at android.app.ActivityThread.main(ActivityThread.java:8669)
E/AndroidRuntime( 8169):  at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8169):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime( 8169):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/AndroidRuntime( 8169): Caused by: java.lang.IllegalArgumentException: Unsupported value: 'F0:A9:68:02:FF:54' of type 'class android.bluetooth.BluetoothDevice'
E/AndroidRuntime( 8169):  at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/AndroidRuntime( 8169):  at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime( 8169):  at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime( 8169):  at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:40)
E/AndroidRuntime( 8169):  at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:122)
E/AndroidRuntime( 8169):  at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:105)
E/AndroidRuntime( 8169):  at de.kevlatus.flutter_broadcasts.MethodCallHandlerImpl$onStartReceiver$1$1.invoke(FlutterBroadcastsPlugin.kt:123)
E/AndroidRuntime( 8169):  at de.kevlatus.flutter_broadcasts.MethodCallHandlerImpl$onStartReceiver$1$1.invoke(FlutterBroadcastsPlugin.kt:122)
E/AndroidRuntime( 8169):  at de.kevlatus.flutter_broadcasts.CustomBroadcastReceiver.onReceive(FlutterBroadcastsPlugin.kt:40)
E/AndroidRuntime( 8169):  at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1806)
E/AndroidRuntime( 8169):  ... 9 more
```

**Comment by amitkot** [comment]
I opened #3 for fixing this issue by normalizing all unsupported types to strings.

**Comment by kevlatus** [comment]
thanks for your contribution, @amitkot!
I just merged your PR and will update the pub package any minute
